type = "card"
title = "Honors"
description = "Selected honors and awards I have received."

[[items]]
title = "National Inspiration Scholarship"
date = "2020 & 2021 & 2023"
subtitle = "Guangdong Provincial Department of Education"

[[items]]
title = "2nd Provincial Prize, Material Heat Treatment Innovation and Entrepreneurship Competition"
date = "2024"
subtitle = "Chinese Mechanical Engineering Society"
content = "Development of Corrosion-Resistant Coatings for Q235 Steel in Marine Environments Based on Laser Heat Treatment. "

[[items]]
title = "1st Provincial Prize, China College Students' 'Internet+'Innovation and Entrepreneurship Competition"
date = "2021"
subtitle = "Guangdong Provincial Department of Education"
content = "A Multi-Module Mechatronics Education and Training Platform."

[[items]]
title = "Outstanding Award, Kingsoft Office Cup – China Computer Application Technology Competition"
date = "2023"
subtitle = "Computer Applications Committee, China Computer Federation (CCF)"

[[items]]
title = "Second-Class Scholarship"
date = "2020 & 2021 & 2023"

[[items]]
title = "Third-Class Scholarship"
date = "2020 & 2021"

[[items]]
title = "Outstanding Graduation Thesis"
date = "2024"
subtitle = "Lingnan Normal University"

[[items]]
title = "Outstanding Intern"
date = "2024"
subtitle = "Lingnan Normal University"
