type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "National Inspiration Scholarship"
date = "2020 & 2021 & 2023"

[[items]]
title = "2nd Provincial Prize, Material Heat Treatment Innovation and Entrepreneurship Competition"
date = "2024"
content = "Contributed to studying the effects of laser power and scanning speed on ceramic coating morphology, identifying optimal parameters to prevent cracking and delamination. "

[[items]]
title = "1st Provincial Prize, China College Students' 'Internet+'Innovation and Entrepreneurship Competition"
date = "2021"
content = "Responsible for drafting the business proposal, iterating the practical training platform solution for target universities, and conducting business and data analysis."

[[items]]
title = "Second-Class Scholarship"
date = "2020 & 2021 & 2023"

[[items]]
title = "Third-Class Scholarship"
date = "2020 & 2021"

[[items]]
title = "Outstanding Graduation Thesis"
date = "2024"

[[items]]
title = "Outstanding Intern"
date = "2024"
