type = "card"
title = "证书"
description = "我曾获得的技能证书。"

[[items]]
title = "工业机器人应用编程职业技能中级等级证书"
date = "2022"
tags = ["工业机器人", "机器人控制"]

[[items]]
title = "ABB Ability智能设备应用中级能力"
date = "2021"
tags = ["ABB机器人", "机器人控制"]

[[items]]
title = "CEAC信息化工程师职业技能培训测评证书"
date = "2021"
tags = ["Python", "嵌入式编程"]

[[items]]
title = "低压电工操作证"
date = "2021"
tags = ["低压电工", "传感器接口"]

[[items]]
title = "普通话二级甲等"
date = "2021"
tags = ["语言"]